import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { promises as fs } from "fs";
import LettersDisplay from "../components/LetterDisplay";
import Menu, { MenuSelection } from "../components/Menu";
import PhrasesDisplay from "../components/PhrasesDisplay";
import useAppState from "../data/app-state";
import TypingDisplay from "../components/TypingDisplay";

export async function getStaticProps() {
  const data = await fs.readFile("public/words.txt", "utf8");

  return {
    props: { words: data.split("\n") }, // will be passed to the page component as props
  };
}
interface NextPageProps {
  words: string[];
}

const Home: NextPage<NextPageProps> = ({ words }: NextPageProps) => {
  const [appState, setAppState] = useAppState();
  const [currentMenuSelection, setCurrentMenuSelection] =
    useState<MenuSelection>(appState.mode);

  return (
    <div className=" h-screen">
      <Head>
        <title>SpeakEasy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-full w-full m-0 p-0">
        <Menu
          current={appState.mode}
          onChange={(mode) => setAppState({ ...appState, mode })}
        >
          <input
            className="h-full w-20 text-3xl mt-2 ml-2 text-center bg-slate-800 text-white rounded-md shadow-md"
            type="text"
            onChange={(e) =>
              setAppState({ ...appState, speed: +e.target.value })
            }
            value={appState.speed}
            placeholder="Speed (higher is slower)"
          />
        </Menu>
        <div className="mt-20 h-full">
          {appState.mode === "Letters" && (
            <LettersDisplay
              play={appState.speed > 0}
              words={words}
              speedMs={(appState.speed > 0 ? appState.speed : 2) * 1000}
            />
          )}

          {appState.mode === "Phrases" && (
            <PhrasesDisplay
              play={appState.speed > 0}
              speedMs={(appState.speed > 0 ? appState.speed : 2) * 1000}
            />
          )}

          {appState.mode === "Typing" && <TypingDisplay />}
        </div>
      </main>
    </div>
  );
};

export default Home;
